// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Episode struct {
	ID        int32          `json:"id"`
	TvShowID  int32          `json:"tv_show_id"`
	Season    int32          `json:"season"`
	Episode   int32          `json:"episode"`
	Released  pgtype.Date    `json:"released"`
	Name      string         `json:"name"`
	Plot      string         `json:"plot"`
	AvgRating pgtype.Numeric `json:"avg_rating"`
	VoteCount int32          `json:"vote_count"`
}

type TvShow struct {
	ID         int32            `json:"id"`
	Name       string           `json:"name"`
	TtImdb     string           `json:"tt_imdb"`
	Popularity int32            `json:"popularity"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
