// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CheckTVShowExists(ctx context.Context, ttImdb string) (TvShow, error)
	CreateEpisodes(ctx context.Context, arg CreateEpisodesParams) (Episode, error)
	CreateTVShow(ctx context.Context, arg CreateTVShowParams) (TvShow, error)
	GetEpisodes(ctx context.Context, tvShowID int32) ([]Episode, error)
	IncreasePopularity(ctx context.Context, ttImdb string) error
	SeasonAverageRating(ctx context.Context, arg SeasonAverageRatingParams) (float64, error)
	SeasonMedianRating(ctx context.Context, arg SeasonMedianRatingParams) (float64, error)
	TvShowAverageRating(ctx context.Context, tvShowID int32) (float64, error)
	TvShowMedianRating(ctx context.Context, tvShowID int32) (float64, error)
}

var _ Querier = (*Queries)(nil)
