version: "3"

services:
  core:
    container_name: rating-orama
    image: rating-orama:latest
    depends_on:
      db:
        condition: service_started
    environment:
      DRIVERNAME: pgx
      DATASOURCE: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      MIGRATE: true
      TITLE_SELECTOR: ${TITLE_SELECTOR}
      SEASON_SELECTOR: ${SEASON_SELECTOR}
      EPISODE_CARD_SELECTOR: ${EPISODE_CARD_SELECTOR}
      SEASON_EPISODE_AND_TITLE_SELECTOR: ${SEASON_EPISODE_AND_TITLE_SELECTOR}
      RELEASED_DATE_SELECTOR: ${RELEASED_DATE_SELECTOR}
      PLOT_SELECTOR: ${PLOT_SELECTOR}
      STAR_RATING_SELECTOR: ${STAR_RATING_SELECTOR}
      VOTE_COUNT_SELECTOR: ${VOTE_COUNT_SELECTOR}
      IMDB_EPISODES_URL: ${IMDB_EPISODES_URL}
      VISIT_URL: ${VISIT_URL}
    ports:
      - "8086:8080"
    networks:
      - ratingorama
  db:
    container_name: db-ratingorama
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ratingorama_data:/var/lib/postgresql/data
    networks:
      - ratingorama

networks:
  ratingorama:

volumes:
  ratingorama_data:

